import "../style/globals.scss";

export const metadata = {
  title: "Todo List",
  description: "This is Todo List Applicatin Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
