import Link from "next/link";
import React from "react";

export const metadata = {
  title: "Register",
  description: "This is Register Page of Todo List  Generated by Next.js",
};

const page = () => {
  return (
    <div className="login">
      <section>
        <form>
          <input type="email" placeholder="enter your email" />
          <input type="password" placeholder="enter your password" />
          <button type="submit">Create New Account</button>
          <p>or</p>
          <Link href={"/login"}>Already I have account </Link>
        </form>
      </section>
    </div>
  );
};

export default page;
