export const metadata = {
  title: "Todo List.",
  description: "This is Todo List Fast Application Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
